name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build AppImage
        run: nix build .#neovim-appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: nvim-bundle.AppImage
          path: ./result

